apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-app
spec:
  selector:
    matchLabels: 
      app: nodejs-app
  template:
    metadata:
      labels:
        app: nodejs-app
    spec:
      containers:
        - name: nodejs-app-container
          image: devopsedu/employee
          ports:
            - containerPort: 8888
          env:
            - name: MONGO_URL
              value: "mongo:27017"
