kind: PersistentVolume
apiVersion: v1
metadata:
  name: mongo
  labels:
    type: local
    app: mongo
spec:
  storageClassName: standard
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/mongo"

---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mongo-claim
  labels:
    app: mongo
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
